/**
 * anti_ai_tell_scanner.js
 * =======================
 * Pure Client-Side Anti-AI Buzzword & Tone Auditor for SPrav Job AI.
 *
 * In 2025/2026, recruiters and hiring managers immediately flag or reject resumes
 * that contain dead-giveaway LLM phrases and generic buzzwords.
 *
 * This engine:
 * 1. Audits resume bullet points against 50 high-confidence AI buzzword tells.
 * 2. Computes a deterministic "Human Voice Score" (0–100%).
 * 3. Quantifies metric density (the presence of numbers, %, $, and scale markers).
 * 4. Provides actionable, 1-click humanized engineering rewrites.
 *
 * 100% Client-Side • $0 Server Cost • Zero Data Leaves Browser
 */

export const AI_BUZZWORD_CATALOG = [
  {
    phrase: 'spearheaded',
    severity: 'high',
    reason: 'Overused LLM action verb; signals automated drafting.',
    alternatives: ['led', 'engineered', 'directed', 'built', 'orchestrated']
  },
  {
    phrase: 'delved',
    severity: 'high',
    reason: 'Classic ChatGPT tell word almost never used in natural technical speech.',
    alternatives: ['investigated', 'analyzed', 'profiled', 'explored', 'audited']
  },
  {
    phrase: 'delve',
    severity: 'high',
    reason: 'Classic ChatGPT tell word.',
    alternatives: ['investigate', 'analyze', 'examine', 'profile']
  },
  {
    phrase: 'tapestry',
    severity: 'high',
    reason: 'Metaphorical fluff generated almost exclusively by generative LLMs.',
    alternatives: ['architecture', 'system', 'ecosystem', 'framework']
  },
  {
    phrase: 'instrumental in',
    severity: 'high',
    reason: 'Vague attribution common in LLM-generated summaries.',
    alternatives: ['responsible for', 'key contributor to', 'engineered', 'delivered']
  },
  {
    phrase: 'testament to',
    severity: 'high',
    reason: 'Pretentious AI trope; recruiters prefer direct metric results.',
    alternatives: ['demonstrating', 'resulting in', 'yielding', 'achieving']
  },
  {
    phrase: 'fostered',
    severity: 'medium',
    reason: 'Generic soft skill buzzword frequently inserted by AI resume generators.',
    alternatives: ['built', 'established', 'mentored', 'instituted', 'grew']
  },
  {
    phrase: 'pioneered',
    severity: 'high',
    reason: 'Over-dramatic verb typical of unaligned LLM prompts.',
    alternatives: ['designed', 'created', 'introduced', 'implemented']
  },
  {
    phrase: 'seamlessly',
    severity: 'high',
    reason: 'Adverbial hype; software integration is rarely truly seamless.',
    alternatives: ['directly', 'with zero downtime', 'reliably', 'cleanly']
  },
  {
    phrase: 'multifaceted',
    severity: 'high',
    reason: 'AI filler adjective with zero technical specificity.',
    alternatives: ['cross-functional', 'end-to-end', 'distributed', 'hybrid']
  },
  {
    phrase: 'game-changer',
    severity: 'high',
    reason: 'Marketing hyperbole.',
    alternatives: ['high-impact', 'foundational', 'critical milestone']
  },
  {
    phrase: 'holistic',
    severity: 'medium',
    reason: 'Vague corporate buzzword favored by AI text generation.',
    alternatives: ['comprehensive', 'full-stack', 'system-wide', 'end-to-end']
  },
  {
    phrase: 'synergy',
    severity: 'high',
    reason: 'Empty buzzword.',
    alternatives: ['integration', 'collaboration', 'alignment', 'cohesion']
  },
  {
    phrase: 'harnessing',
    severity: 'high',
    reason: 'Literary flourish common in LLM summaries.',
    alternatives: ['using', 'leveraging', 'applying', 'deploying']
  },
  {
    phrase: 'revolutionized',
    severity: 'high',
    reason: 'Unsubstantiated hyperbole flagged by technical interviewers.',
    alternatives: ['transformed', 'redesigned', 'migrated', 'optimized']
  },
  {
    phrase: 'beacon of',
    severity: 'high',
    reason: 'Extravagant praise trope generated by models.',
    alternatives: ['standard for', 'reference model for', 'benchmark']
  },
  {
    phrase: 'paramount',
    severity: 'high',
    reason: 'Formal filler word typical of AI generated cover letters and profiles.',
    alternatives: ['critical', 'essential', 'top priority', 'vital']
  },
  {
    phrase: 'pivotal',
    severity: 'medium',
    reason: 'Over-used dramatic verb modifier.',
    alternatives: ['key', 'central', 'core', 'critical']
  },
  {
    phrase: 'intertwined',
    severity: 'high',
    reason: 'Literary phrasing not suited for engineering documentation.',
    alternatives: ['coupled', 'integrated', 'connected', 'interdependent']
  },
  {
    phrase: 'transformative',
    severity: 'medium',
    reason: 'Generic praise adjective.',
    alternatives: ['high-ROI', 'modernized', 'high-efficiency']
  },
  {
    phrase: 'plethora of',
    severity: 'high',
    reason: 'Pseudo-intellectual AI vocabulary.',
    alternatives: ['multiple', 'numerous', 'diverse range of', 'several']
  },
  {
    phrase: 'passionate about',
    severity: 'medium',
    reason: 'Cliché opener rejected by modern technical recruiters.',
    alternatives: ['specializing in', 'focused on', 'experienced with']
  },
  {
    phrase: 'adept at',
    severity: 'medium',
    reason: 'Weak generic descriptor.',
    alternatives: ['proficient with', 'proven track record in', 'skilled in']
  },
  {
    phrase: 'catalyst for',
    severity: 'medium',
    reason: 'Overwrought corporate metaphor.',
    alternatives: ['driver of', 'responsible for', 'instigator of']
  },
  {
    phrase: 'dynamic environment',
    severity: 'medium',
    reason: 'Vacuous filler phrase.',
    alternatives: ['fast-paced team', 'high-growth environment', 'production system']
  },
  {
    phrase: 'realm of',
    severity: 'high',
    reason: 'Fantasy/fiction framing common in raw LLM outputs.',
    alternatives: ['domain of', 'field of', 'area of', 'space of']
  },
  {
    phrase: 'navigated the complexities',
    severity: 'high',
    reason: 'Dramatic AI narrative style.',
    alternatives: ['resolved', 'managed', 'debugged', 'architected']
  },
  {
    phrase: 'deep dive',
    severity: 'medium',
    reason: 'Overused corporate colloquialism.',
    alternatives: ['in-depth analysis', 'investigation', 'root cause audit']
  },
  {
    phrase: 'cutting-edge',
    severity: 'medium',
    reason: 'Vague jargon without technical substance.',
    alternatives: ['modern', 'state-of-the-art', 'emerging', 'next-generation']
  },
  {
    phrase: 'state-of-the-art',
    severity: 'medium',
    reason: 'Common LLM praise phrase.',
    alternatives: ['modern', 'production-grade', 'high-performance']
  },
  {
    phrase: 'leveraged',
    severity: 'medium',
    reason: 'Very frequent in AI resumes; better to use exact verbs.',
    alternatives: ['utilized', 'applied', 'deployed', 'implemented']
  },
  {
    phrase: 'orchestrated a seamless',
    severity: 'high',
    reason: 'Dramatic double-AI tell.',
    alternatives: ['managed a clean', 'executed an automated', 'completed a']
  },
  {
    phrase: 'empowered the team',
    severity: 'medium',
    reason: 'Soft generic assertion without proof.',
    alternatives: ['unblocked the team', 'automated workflows so team could', 'trained']
  },
  {
    phrase: 'poised to',
    severity: 'high',
    reason: 'Predictive fluff.',
    alternatives: ['ready to', 'qualified to', 'prepared to']
  },
  {
    phrase: 'at the forefront of',
    severity: 'high',
    reason: 'Grandiose filler.',
    alternatives: ['working on', 'specializing in', 'building']
  },
  {
    phrase: 'resonate with',
    severity: 'medium',
    reason: 'Vague psychological trope.',
    alternatives: ['align with', 'support', 'meet requirements of']
  },
  {
    phrase: 'unwavering commitment',
    severity: 'high',
    reason: 'AI melodrama.',
    alternatives: ['focus on', 'priority for', 'dedication to']
  },
  {
    phrase: 'rich history of',
    severity: 'high',
    reason: 'AI storytelling trope.',
    alternatives: ['track record of', 'background in', 'career history of']
  },
  {
    phrase: 'steep learning curve',
    severity: 'medium',
    reason: 'Negative framing cliché.',
    alternatives: ['rapidly mastered', 'quickly adopted', 'upskilled on']
  },
  {
    phrase: 'unparalleled',
    severity: 'high',
    reason: 'Unprovable superlative.',
    alternatives: ['exceptional', 'industry-standard', 'benchmark']
  },
  {
    phrase: 'masterminded',
    severity: 'high',
    reason: 'Cartoonish villain/hero trope in AI resumes.',
    alternatives: ['architected', 'designed', 'directed', 'devised']
  },
  {
    phrase: 'groundbreaking',
    severity: 'high',
    reason: 'Extreme hyperbole.',
    alternatives: ['novel', 'first-of-its-kind', 'high-impact']
  },
  {
    phrase: 'transcended',
    severity: 'high',
    reason: 'Philosophical fluff.',
    alternatives: ['exceeded', 'surpassed', 'improved beyond']
  },
  {
    phrase: 'indispensable asset',
    severity: 'high',
    reason: 'Self-praising cliché.',
    alternatives: ['core contributor', 'subject matter expert', 'lead developer']
  },
  {
    phrase: 'paragon of',
    severity: 'high',
    reason: 'Antiquated AI vocabulary.',
    alternatives: ['example of', 'standard of', 'model of']
  },
  {
    phrase: 'in a nutshell',
    severity: 'high',
    reason: 'Conversational informal filler.',
    alternatives: ['in summary', 'specifically', 'primarily']
  },
  {
    phrase: 'quintessential',
    severity: 'high',
    reason: 'Thesaurus stuffing by LLMs.',
    alternatives: ['archetypal', 'ideal', 'standard']
  },
  {
    phrase: 'breathed new life into',
    severity: 'high',
    reason: 'Poetic AI metaphor.',
    alternatives: ['refactored', 'revitalized', 'modernized', 'optimized']
  },
  {
    phrase: 'cornerstone of',
    severity: 'medium',
    reason: 'Common architectural cliché.',
    alternatives: ['core component of', 'foundation of', 'key element of']
  },
  {
    phrase: 'relentlessly',
    severity: 'high',
    reason: 'Melodramatic adverb.',
    alternatives: ['consistently', 'systematically', 'rigorously']
  }
];

/**
 * Checks if a string contains hard quantitative metrics (numbers, %, $, ms, etc.).
 * @param {string} text
 * @returns {boolean}
 */
export function hasQuantitativeMetrics(text) {
  if (!text) return false;
  // Match numbers, percentages, dollar amounts, multiples (3x), latencies (20ms, 1.2s), volume (10M, 2B)
  const metricRegex = /(\b\d+(\.\d+)?\b|\b\d+%\b|\$\d+|\b\d+[xX]\b|\b\d+(\.\d+)?(ms|s|gb|mb|tb|k|m|b)\b)/i;
  return metricRegex.test(text);
}

/**
 * Audits text or bullet points for AI buzzwords and computes a Human Voice Score.
 *
 * @param {string | string[]} input - Resume string or array of bullet points
 * @returns {object} Audit report with scores, flagged items, and rewrite suggestions
 */
export function auditAntiAiTone(input) {
  const bullets = Array.isArray(input)
    ? input.map(b => String(b || '').trim()).filter(Boolean)
    : String(input || '')
        .split('\n')
        .map(b => b.trim().replace(/^[•\-\*]\s*/, ''))
        .filter(Boolean);

  if (bullets.length === 0) {
    return {
      humanVoiceScore: 100,
      metricDensity: 100,
      totalBullets: 0,
      flaggedWords: [],
      severityCount: { high: 0, medium: 0 },
      isAiLikely: false,
      summary: 'Authentic Human Voice (No text to evaluate).'
    };
  }

  const flaggedWords = [];
  let bulletsWithMetrics = 0;

  bullets.forEach((bullet, bIdx) => {
    if (hasQuantitativeMetrics(bullet)) {
      bulletsWithMetrics++;
    }

    const lowerBullet = bullet.toLowerCase();

    for (const item of AI_BUZZWORD_CATALOG) {
      const phraseLower = item.phrase.toLowerCase();
      // Match whole word / boundary
      const escaped = phraseLower.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&');
      const regex = new RegExp(`\\b${escaped}\\b`, 'gi');

      let match;
      while ((match = regex.exec(lowerBullet)) !== null) {
        // Extract context window around match
        const start = Math.max(0, match.index - 20);
        const end = Math.min(bullet.length, match.index + phraseLower.length + 20);
        const snippet = (start > 0 ? '...' : '') + bullet.slice(start, end).trim() + (end < bullet.length ? '...' : '');

        flaggedWords.push({
          word: item.phrase,
          matchedText: bullet.slice(match.index, match.index + phraseLower.length),
          bulletIndex: bIdx,
          severity: item.severity,
          reason: item.reason,
          alternatives: item.alternatives,
          snippet
        });
      }
    }
  });

  const metricDensity = Math.round((bulletsWithMetrics / bullets.length) * 100);
  const highSeverityCount = flaggedWords.filter(f => f.severity === 'high').length;
  const mediumSeverityCount = flaggedWords.filter(f => f.severity === 'medium').length;

  // Score computation: Starts at 100.
  // High penalty: -8 pts per high severity buzzword.
  // Medium penalty: -4 pts per medium severity buzzword.
  // Metric boost/penalty: if metric density is < 40%, penalty up to -20 pts.
  let penalty = (highSeverityCount * 8) + (mediumSeverityCount * 4);
  if (metricDensity < 40) {
    penalty += Math.round((40 - metricDensity) * 0.5);
  }

  const humanVoiceScore = Math.max(0, Math.min(100, 100 - penalty));
  const isAiLikely = humanVoiceScore < 70 || highSeverityCount >= 3;

  let summary = '100% Authentic Human Voice — Clean engineering cadence with strong metric density.';
  if (humanVoiceScore < 60) {
    summary = '⚠️ High AI Tell Density — Multiple dead-giveaway LLM phrases detected. Immediate humanization recommended.';
  } else if (humanVoiceScore < 85) {
    summary = '🟡 Moderate Buzzword Density — Some generic AI filler detected. Consider replacing with precise technical verbs.';
  }

  return {
    humanVoiceScore,
    metricDensity,
    totalBullets: bullets.length,
    flaggedWords,
    severityCount: {
      high: highSeverityCount,
      medium: mediumSeverityCount
    },
    isAiLikely,
    summary
  };
}

/**
 * 1-Click auto-humanizer that replaces dead-giveaway AI buzzwords with authentic verbs.
 *
 * @param {string} text - Input text or bullet point
 * @returns {string} Humanized text
 */
export function humanizeAiText(text) {
  if (!text) return '';
  let result = String(text);

  for (const item of AI_BUZZWORD_CATALOG) {
    const escaped = item.phrase.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&');
    const regex = new RegExp(`\\b${escaped}\\b`, 'gi');
    const replacement = item.alternatives[0] || 'led';

    result = result.replace(regex, (match) => {
      // Preserve uppercase first letter if present in source
      if (match[0] === match[0].toUpperCase()) {
        return replacement.charAt(0).toUpperCase() + replacement.slice(1);
      }
      return replacement;
    });
  }

  return result;
}
